name: myAction
on:
  push:
    branches: [master]
jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: clone repo
        uses: actions/checkout@v4
      - name: install dep
        run: npm ci
      - name: test
        id: test
        run: npm run test
      - name: upload report
        if: failure() && steps.test.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: test.json       
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: clone repo
        uses: actions/checkout@v4
      - name: install dep
        run: npm ci
