name: myAction
on:
  push:
    branches: [master]
jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: clone repo
        uses: actions/checkout@v4
      - name: install dep
        run: npm ci
      - name: test
        id: test
        run: npm run test
      - name: upload report
        if: failure() && steps.test.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: test.json       
 build:
  strategy:
   matrix:
    node-version: [14]
    opsys: [ubuntu-latest, windows-latest]
    exclude:
     - node-version: 12
       operating-system: windows-latest
    include:
     - node-version: 18
       operating-system: ubuntu-latest  
  runs-on: ${{matrix.opsys}}
  steps:
   - name: Clone the code 
     uses: actions/checkout@v3
   - name: Install nodeJS 
     uses: actions/setup-node@v3
     with:
      node-version: ${{matrix.node-version}}
   - name: Install dependencies 
     run: npm ci
   - name: Build the code 
     run: npm run build
